name: badge

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install stable toolchain
      uses: dtolnay/rust-toolchain@stable
    - name: Run cargo test
      run: cargo test --all --all-features
