name: Fast PR check

on:
  pull_request:
    types: [ opened, edited ]
    branches: [ master ]
    paths: 
      - '**.rs'
      - '**/Cargo.toml'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install stable toolchain
      uses: dtolnay/rust-toolchain@stable
    - name: Check no_std 
      run: cargo check --manifest-path gpu-descriptor/Cargo.toml --no-default-features
    - name: Run cargo test
      run: cargo test --all --all-features
