name: Lints

on:
  pull_request:
    types: [ opened, edited ]
    branches: [ master ]
    paths: 
      - '**.rs'
      - '**/Cargo.toml'

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install nightly toolchain
      uses: dtolnay/rust-toolchain@nightly
      with:
        components: rustfmt
    - name: Run cargo fmt
      run: cargo fmt --all -- --check

  cllippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install nightly toolchain with clippy available
      uses: dtolnay/rust-toolchain@nightly
      with:
        components: clippy
    - name: Run cargo clippy
      run: cargo clippy --all --all-features -- -D warnings
